### ISSUE TITLE
I followed the quick start and it has failed to work

### ISSUE THREAD

**Issue by finalclass** [thundernet8/Generator-TS-React#1]
```
$ yo ts-react
 generator-ts-react v1.2.3
 question:name: exercises
 question:description: 
 question:main: (index.js) 
 question:author (name <email>): 
 question:license: (MIT) 
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, copyfile '/home/sel/.nvm/versions/node/v8.9.0/lib/node_modules/generator-ts-react/app/archive/postcss.config.js' -> '/home/sel/gdrive/complete-web-dev/exercises'
    at Object.fs.copyFileSync (fs.js:1910:11)
    at /home/sel/.nvm/versions/node/v8.9.0/lib/node_modules/generator-ts-react/app/index.js:145:16
    at Array.forEach (<anonymous>)
    at module.exports.copyFiles (/home/sel/.nvm/versions/node/v8.9.0/lib/node_modules/generator-ts-react/app/index.js:144:48)
    at Object.<anonymous> (/home/sel/.nvm/versions/node/v8.9.0/lib/node_modules/generator-ts-react/node_modules/yeoman-generator/lib/index.js:399:25)
    at /home/sel/.nvm/versions/node/v8.9.0/lib/node_modules/generator-ts-react/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/sel/.nvm/versions/node/v8.9.0/lib/node_modules/generator-ts-react/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/sel/.nvm/versions/node/v8.9.0/lib/node_modules/generator-ts-react/node_modules/yeoman-generator/lib/index.js:400:11)
    at runCallback (timers.js:789:20)
```
I'm on arch linux.

**Comment by thundernet8** [comment]
@finalclass reinstall this generator package globally, it's been updated

**Comment by finalclass** [comment]
@thundernet8 Thanks!
The installation went smooth and the generated seed is amazing. Thank you for sharing this generator.
